on:
  push:
    branches:
    - master
    - main
    - "cran-*"
    #- "r-*"
    tags:
    - "v*"
  schedule:
    - cron:  '20 0 * * *'

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-18.04

    # Begin custom: services
    # End custom: services
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-tinytex@v1

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: pkgdown
          needs: website

      - name: Configure Git identity
        run: |
          env | sort
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        shell: bash


      - name: Build and deploy pkgdown site
        run: |
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
